[package]
name = "luna-machine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
luna-diag = { path = "../diag" }
luna-isa = { path = "../isa" }
luna-memory = { path = "../memory" }
luna-floatfmt = { path = "../floatfmt" }
luna-target-api = { path = "../target-api" }

[lints]
workspace = true
