[package]
name = "luna-app"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
luna-assembler = { path = "../assembler" }
luna-machine = { path = "../machine" }
luna-monitor = { path = "../monitor" }
luna-qemu-backend = { path = "../qemu-backend" }

[lints]
workspace = true
