#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

command -v asciinema >/dev/null || { printf 'asciinema is required\n' >&2; exit 2; }
command -v tmux >/dev/null || { printf 'tmux is required\n' >&2; exit 2; }
command -v script >/dev/null || { printf 'script is required\n' >&2; exit 2; }

commit="$(git rev-parse HEAD)"
short_commit="$(git rev-parse --short HEAD)"
output_dir="${1:-artifacts/audit/${short_commit}-tmux}"
mkdir -p "$output_dir"
cast="$output_dir/tutorial-guest-tmux.cast"
transcript="$output_dir/tutorial-guest-tmux.txt"
manifest="$output_dir/tutorial-guest-tmux-manifest.toml"
pause_seconds="${TUTORIAL_GUEST_PAUSE:-1}"
timeout_seconds="${TUTORIAL_GUEST_TIMEOUT:-360}"

cargo build -p luna-guest-monitor --target riscv64gc-unknown-none-elf >/dev/null

# asciinema starts its command through the user's shell.  Force Bash here so a
# host-specific interactive Fish configuration cannot pollute the audit cast.
export SHELL=/bin/bash
asciinema rec --overwrite \
    --title "RVMonitor guest tutorial / tmux source + QEMU / $short_commit" \
    --command "env TUTORIAL_GUEST_PAUSE=$pause_seconds TUTORIAL_GUEST_TIMEOUT=$timeout_seconds bash scripts/tutorial-guest-tmux-record-command.sh" \
    "$cast"
asciinema convert --overwrite --output-format txt "$cast" "$transcript"
bash scripts/check-tutorial-tmux-cast.sh "$cast"

cast_sha256="$(sha256sum "$cast" | awk '{print $1}')"
transcript_sha256="$(sha256sum "$transcript" | awk '{print $1}')"
{
    printf '# Generated by scripts/record-tutorial-guest-tmux.sh\n'
    printf 'schema_version = 1\n'
    printf 'project = "rvmonitor"\n'
    printf 'git_commit = "%s"\n' "$commit"
    printf 'profile = "RV64ILP32D-MON-1"\n'
    printf 'layout = "tmux: top 30%% tutorial source / bottom 70%% QEMU guest"\n'
    printf 'pause_seconds = %s\n' "$pause_seconds"
    printf 'timeout_seconds = %s\n' "$timeout_seconds"
    printf 'cast_file = "%s"\n' "$(basename "$cast")"
    printf 'cast_sha256 = "%s"\n' "$cast_sha256"
    printf 'transcript_file = "%s"\n' "$(basename "$transcript")"
    printf 'transcript_sha256 = "%s"\n' "$transcript_sha256"
    printf 'asciinema_version = "%s"\n' "$(asciinema --version)"
    printf 'tmux_version = "%s"\n' "$(tmux -V)"
    printf 'qemu_version = "%s"\n' "$(qemu-system-riscv64 --version | tr '\n' ' ')"
    printf 'rustc_version = "%s"\n' "$(rustc --version)"
    printf 'purpose = "step-synchronized French tutorial source above a real QEMU guest session"\n'
} > "$manifest"

printf 'tmux tutorial audit artifacts written to %s\n' "$output_dir"
