#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

command -v asciinema >/dev/null || { printf 'asciinema is required\n' >&2; exit 2; }
command -v qemu-system-riscv64 >/dev/null || { printf 'qemu-system-riscv64 is required\n' >&2; exit 2; }

commit="$(git rev-parse HEAD)"
short_commit="$(git rev-parse --short HEAD)"
output_dir="${1:-artifacts/audit/$short_commit}"
mkdir -p "$output_dir"
cast="$output_dir/minibasic-hammurabi.cast"
transcript="$output_dir/minibasic-hammurabi.txt"
manifest="$output_dir/manifest.toml"

cargo build -p luna-guest-monitor --target riscv64gc-unknown-none-elf >/dev/null
image="target/riscv64gc-unknown-none-elf/debug/luna-guest-monitor"
divide_address="$(riscv64-linux-gnu-nm -n "$image" | awk '$3 == "minibasic_divide" && !found { value=$1; found=1 } END { print value }')"
test -n "$divide_address"

demo_command=$(cat <<EOF
set -e
divide_address=0x$divide_address
{
  sleep 0.3
  printf 'help\\nregs\\nbasic\\n'
  sleep 0.2
  printf 'PRINT 2+3*4\\nPRINT 22/7\\n'
  printf '10 FOR I=1 TO 3\\n20 PRINT I,I/3\\n30 NEXT I\\n40 END\\n'
  printf 'LIST\\nTRACE ON\\nRUN\\nTRACE OFF\\nBYE\\n'
  sleep 0.3
  printf 'break %s\\nbasic\\n' "$divide_address"
  sleep 0.3
  printf '10 I=1\\n20 X=I/3\\n30 PRINT X\\n40 END\\nRUN\\n'
  sleep 0.5
  printf 'regs\\ndisasm %s 12\\nstep\\nregs\\ndelete 1\\ncontinue\\nBYE\\n' "$divide_address"
  sleep 0.4
  printf 'basic\\n' 
  sleep 0.2
  awk '/^### 4.7/{found=1} found && /^\`\`\`basic/{program=1; next} program && /^\`\`\`/{exit} program{print}' \\
    docs/TUTORIAL-GUEST.md | while IFS= read -r line; do
      printf '%s\\n' "\$line"
      sleep 0.015
    done
  sleep 0.3
  printf 'TRACE ON\\nRUN\\n'
  sleep 0.3
  for value in 0 20 190 0 20 190 0 20 190 0 20 190 0 20 190; do
    printf '%s\\n' "\$value"
    sleep 0.12
  done
  sleep 0.3
  printf 'TRACE OFF\\nDUMP\\nBYE\\nq\\n'
} | timeout 35s qemu-system-riscv64 -M virt -m 64M -bios none -kernel "$image" -nographic
EOF
)

asciinema rec --overwrite --title "RVMonitor MiniBASIC Hammurabi / $short_commit" \
  --command "bash -lc $(printf '%q' "$demo_command")" "$cast"
asciinema convert --overwrite --output-format txt "$cast" "$transcript"

cast_sha256="$(sha256sum "$cast" | awk '{print $1}')"
transcript_sha256="$(sha256sum "$transcript" | awk '{print $1}')"
{
  printf '# Generated by scripts/record-minibasic-demo.sh\n'
  printf 'schema_version = 1\n'
  printf 'project = "rvmonitor"\n'
  printf 'git_commit = "%s"\n' "$commit"
  printf 'profile = "RV64ILP32D-MON-1"\n'
  printf 'cast_file = "%s"\n' "$(basename "$cast")"
  printf 'cast_sha256 = "%s"\n' "$cast_sha256"
  printf 'transcript_file = "%s"\n' "$(basename "$transcript")"
  printf 'transcript_sha256 = "%s"\n' "$transcript_sha256"
  printf 'asciinema_version = "%s"\n' "$(asciinema --version)"
  printf 'qemu_version = "%s"\n' "$(qemu-system-riscv64 --version | tr '\n' ' ')"
  printf 'rustc_version = "%s"\n' "$(rustc --version)"
  printf 'symbol_minibasic_divide = "0x%s"\n' "$divide_address"
  printf 'purpose = "real target-side MiniBASIC and Hammurabi guest monitoring session"\n'
} > "$manifest"

printf 'audit artifacts written to %s\n' "$output_dir"
printf 'cast: %s\ntranscript: %s\nmanifest: %s\n' "$cast" "$transcript" "$manifest"
