#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

command -v asciinema >/dev/null || { printf 'asciinema is required\n' >&2; exit 2; }
commit="$(git rev-parse HEAD)"
short_commit="$(git rev-parse --short HEAD)"
output_dir="${1:-artifacts/audit/$short_commit}"
mkdir -p "$output_dir"
cast="$output_dir/tutorial-guest.cast"
transcript="$output_dir/tutorial-guest.txt"
manifest="$output_dir/tutorial-manifest.toml"
pause_seconds="${TUTORIAL_GUEST_PAUSE:-1}"

cargo build -p luna-guest-monitor --target riscv64gc-unknown-none-elf >/dev/null
if [[ "${REUSE_CAST:-0}" == 1 && -s "$cast" ]]; then
    printf 'reusing existing cast %s\n' "$cast"
else
asciinema rec --overwrite --title "RVMonitor guest tutorial / $short_commit" \
        --command "bash scripts/tutorial-guest-session.sh" "$cast"
fi
asciinema convert --overwrite --output-format txt "$cast" "$transcript"
bash scripts/check-tutorial-transcript.sh "$transcript"

cast_sha256="$(sha256sum "$cast" | awk '{print $1}')"
transcript_sha256="$(sha256sum "$transcript" | awk '{print $1}')"
{
    printf '# Generated by scripts/record-tutorial-guest.sh\n'
    printf 'schema_version = 1\n'
    printf 'project = "rvmonitor"\n'
    printf 'git_commit = "%s"\n' "$commit"
    printf 'profile = "RV64ILP32D-MON-1"\n'
    printf 'pause_seconds = %s\n' "$pause_seconds"
    printf 'cast_file = "%s"\n' "$(basename "$cast")"
    printf 'cast_sha256 = "%s"\n' "$cast_sha256"
    printf 'transcript_file = "%s"\n' "$(basename "$transcript")"
    printf 'transcript_sha256 = "%s"\n' "$transcript_sha256"
    printf 'asciinema_version = "%s"\n' "$(asciinema --version)"
    printf 'qemu_version = "%s"\n' "$(qemu-system-riscv64 --version | tr '\n' ' ')"
    printf 'rustc_version = "%s"\n' "$(rustc --version)"
    printf 'purpose = "step-by-step recording of docs/TUTORIAL-GUEST.md"\n'
} > "$manifest"

printf 'tutorial audit artifacts written to %s\n' "$output_dir"
