#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

output_dir="docs/release"
check_only=0
if [[ "${1:-}" == "--check" ]]; then
    check_only=1
    output_dir="$(mktemp -d)"
elif [[ $# -gt 0 ]]; then
    printf 'usage: tools/generate-release-dossier.sh [--check]\n' >&2
    exit 2
fi

input_list="$(mktemp)"
input_hashes="$(mktemp)"
cleanup() {
    rm -f "$input_list" "$input_hashes"
    if ((check_only)); then rm -rf "$output_dir"; fi
}
trap cleanup EXIT
mkdir -p "$output_dir"

manifest="$output_dir/RELEASE-MANIFEST.toml"
sbom="$output_dir/SBOM.tsv"
licenses="$output_dir/LICENSES.md"

# Exclude generated dossier files and ignored artifacts. Sorting makes the
# tree hash independent of filesystem traversal order.
git ls-files | awk '$0 !~ /^docs\/release\// && $0 !~ /^artifacts\// { print }' | sort > "$input_list"
while IFS= read -r path; do sha256sum "$path"; done < "$input_list" > "$input_hashes"
tree_hash="$(sha256sum "$input_hashes" | awk '{print $1}')"
toolchain_hash="$(sha256sum rust-toolchain.toml | awk '{print $1}')"

cat > "$manifest" <<EOF
# Generated by tools/generate-release-dossier.sh; no wall-clock timestamp.
# git_commit identifies the source checkout used to create this dossier; the
# dossier checker ignores that one self-referential field.
schema_version = 1
project = "rvmonitor"
git_commit = "$(git rev-parse HEAD)"
profile = "RV64ILP32D-MON-1"
input_file_count = $(wc -l < "$input_list")
input_tree_sha256 = "$tree_hash"
rust_toolchain_sha256 = "$toolchain_hash"
r2_sources_manifest = "norms/r2/SHA256SUMS"
r2_sources_manifest_sha256 = "$(sha256sum norms/r2/SHA256SUMS | awk '{print $1}')"
format = "RVSNAP01/RVPROJ01 strict v4"
external_oracles = "GNU/LLVM checked separately; Sail/Spike evidence not implied"
EOF

printf 'name\tversion\tlicense\tsource\tchecksum\n' > "$sbom"
for metadata in \
    "$(cargo metadata --format-version 1)" \
    "$(cargo metadata --manifest-path fuzz/Cargo.toml --format-version 1)"; do
    printf '%s' "$metadata" | jq -r '.packages[] | [.name, .version, (.license // "UNKNOWN"), (.source // "workspace"), (.checksum // "-")] | @tsv'
done | sort -u >> "$sbom"

cat > "$licenses" <<'EOF'
# Licences et provenance de release

Ce dossier ne redistribue pas les documents externes R1–R5/A1–A2/C1. Il
référence leurs licences et leur statut dans `docs/SOURCES.toml` et
`norms/manifest.toml`. Toute redistribution d’un document externe reste
conditionnée à la vérification de sa licence.

## Projet

- RVMonitor et ses crates : Apache-2.0 (`Cargo.toml`).
- Fuzz harness : Apache-2.0 (`fuzz/Cargo.toml`).

## Données et normes référencées

- R2 `riscv-opcodes` : BSD-3-Clause, extraits sous `norms/r2/`.
- R3 psABI : CC-BY-4.0, snapshot externe non vendored, statut expérimental.
- R4 Assembly Programmer’s Manual : CC-BY-4.0, référence externe.
- R5 Sail RISC-V : BSD-2-Clause, oracle externe.
- GNU Binutils : GPL-3.0-or-later, oracle indépendant optionnel.
- LLVM : Apache-2.0 WITH LLVM-exception, oracle indépendant optionnel.
- QEMU : GPL-2.0-or-later, oracle sémantique externe.

La liste exacte des crates et checksums est dans `SBOM.tsv`; elle est issue de
`cargo metadata` et de `Cargo.lock`, sans dépendance à un chemin hôte.
EOF

if ((check_only)); then
    expected="$repo_root/docs/release"
    for file in RELEASE-MANIFEST.toml SBOM.tsv LICENSES.md; do
        if [[ "$file" == RELEASE-MANIFEST.toml ]]; then
            cmp -s <(sed '/^git_commit = /d' "$output_dir/$file") \
                <(sed '/^git_commit = /d' "$expected/$file") || {
                printf 'release dossier differs: docs/release/%s\n' "$file" >&2
                exit 1
            }
            continue
        fi
        cmp -s "$output_dir/$file" "$expected/$file" || {
            printf 'release dossier differs: docs/release/%s\n' "$file" >&2
            exit 1
        }
    done
    printf 'release dossier: PASS\n'
else
    printf 'generated release dossier in %s\n' "$output_dir"
fi
